name: Pull request workflow
on: pull_request
jobs:
  install-dependencies:
    runs-on: ubuntu-latest
    steps:
      - name: Get the code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install yarn
        run: npm install -g yarn
      - name: Install project dependencies
        run: yarn install --frozen-lockfile
      - name: Publish to chromatic
        run: yarn chromatic
